### Vector

In [1]:
pass = TRUE

In [2]:
print(class(pass))

[1] "logical"


In [3]:
a = 12.5
b = 150
print(class(a))
print(class(b))

[1] "numeric"
[1] "numeric"


In [4]:
int = 2L
print(class(int))

[1] "integer"


In [6]:
ky_tu = "a"
print(class(ky_tu))

[1] "character"


In [7]:
x = c(123, "cang", 15.5, TRUE, c(1,2,3))

In [8]:
print(class(x))

[1] "character"


### Factor

In [9]:
apple_color = c("green", "green", "red", "red", "yellow", "yellow")

In [10]:
factor_apple = factor(apple_color)

In [11]:
print(factor_apple)

[1] green  green  red    red    yellow yellow
Levels: green red yellow


In [13]:
print(nlevels(factor_apple))

[1] 3


### LIST

In [14]:
list1 = list(c(2,5,3), 20.5, "spring")
print(list1)

[[1]]
[1] 2 5 3

[[2]]
[1] 20.5

[[3]]
[1] "spring"



### MATRIX

In [15]:
M = matrix(c(1,2,3,4,5,6,7,8), nrow=2, ncol=4, byrow = TRUE)

In [16]:
print(M)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8


In [17]:
M1 = matrix(c(1,2,3,4,5,6,7), nrow=3)

Warning message in matrix(c(1, 2, 3, 4, 5, 6, 7), nrow = 3):
“data length [7] is not a sub-multiple or multiple of the number of rows [3]”

In [26]:
print(M1)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    1
[3,]    3    6    2


In [29]:
M1[2,2]

[1] 5

### ARRAY

In [23]:
a = array(c('red', 'green', 'yellow'), dim=c(3,3,2)) #dim la thong tin ma tran. thu tu so dong, so cot, so ma tran

In [22]:
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"

, , 2

     [,1]     [,2]     [,3]    
[1,] "red"    "red"    "red"   
[2,] "green"  "green"  "green" 
[3,] "yellow" "yellow" "yellow"



In [25]:
a[2,2,2]

[1] "green"

### DataFrame

In [30]:
BMI = data.frame(gender = c('male', 'male', 'female'),
                height = c(152, 171, 165.5),
                weight= c(81, 93, 78),
                age = c(32, 42, 30))
print(BMI)

  gender height weight age
1   male  152.0     81  32
2   male  171.0     93  42
3 female  165.5     78  30


In [31]:
?reserved

Reserved                 package:base                  R Documentation

_R_e_s_e_r_v_e_d _W_o_r_d_s _i_n _R

_D_e_s_c_r_i_p_t_i_o_n:

     The reserved words in R's parser are

     ‘if’ ‘else’ ‘repeat’ ‘while’ ‘function’ ‘for’ ‘in’ ‘next’ ‘break’

     ‘TRUE’ ‘FALSE’ ‘NULL’ ‘Inf’ ‘NaN’ ‘NA’ ‘NA_integer_’ ‘NA_real_’
     ‘NA_complex_’ ‘NA_character_’

     ‘...’ and ‘..1’, ‘..2’ etc, which are used to refer to arguments
     passed down from a calling function, see ‘...’.

_D_e_t_a_i_l_s:

     Reserved words outside quotes are always parsed to be references
     to the objects linked to in the ‘Description’, and hence they are
     not allowed as syntactic names (see ‘make.names’).  They *are*
     allowed as non-syntactic names, e.g. inside backtick quotes.

In [32]:
ls()

[1] "a"            "apple_color"  "b"            "BMI"          "factor_apple"
 [6] "int"          "ky_tu"        "list1"        "M"            "M1"          
[11] "pass"         "x"

### Toan tu

In [49]:
v = c(1,6,5.5)
t = c(5,3,10)

In [50]:
print(v + t)

[1]  6.0  9.0 15.5


In [51]:
print(v -t)

[1] -4.0  3.0 -4.5


In [52]:
print(v * t)

[1]  5 18 55


In [53]:
print(v / t)

[1] 0.20 2.00 0.55


In [54]:
#chia lay phan du
print(v %% t)

[1] 1.0 0.0 5.5


In [55]:
# chia lay phan Nguyen
print(v %/% t)

[1] 0 2 0


In [56]:
print ( v ^ t)

[1]        1      216 25329516


In [57]:
v > t

[1] FALSE  TRUE FALSE

In [58]:
v < t

[1]  TRUE FALSE  TRUE

In [59]:
v == t

[1] FALSE FALSE FALSE

In [60]:
v <= t

[1]  TRUE FALSE  TRUE

In [61]:
v >=t

[1] FALSE  TRUE FALSE

In [62]:
v != t

[1] TRUE TRUE TRUE

In [63]:
v = c(3, 1, TRUE, 0)
t = c(4, 1, FALSE, 2)

In [64]:
v & t

[1]  TRUE  TRUE FALSE FALSE

In [65]:
v | t

[1] TRUE TRUE TRUE TRUE

In [67]:
!t

[1] FALSE FALSE  TRUE FALSE

In [68]:
v && t

[1] TRUE

In [69]:
v || t

[1] TRUE

In [70]:
v <- 1:10

In [71]:
v

[1]  1  2  3  4  5  6  7  8  9 10

In [72]:
v1 = 8
v2 = 12

In [73]:
v1 %in% v

[1] TRUE

In [75]:
v2 %in% v

[1] FALSE

In [76]:
a = readline("Nhap ten:")

Nhap ten: cang


In [77]:
a

[1] "cang"

In [78]:
b = readline(prompt="Nhap ten:")

Nhap ten: sy cang


In [79]:
b

[1] "sy cang"

In [80]:
age = as.integer(readline("Nhap tuoi:"))

Nhap tuoi: 30


In [81]:
age

[1] 30

In [82]:
class(age)

[1] "integer"

In [84]:
height = as.numeric(readline("nhap chiu cao"))

nhap chiu cao 56.5


In [85]:
height

[1] 56.5

### STRING

In [86]:
s1 = "Pham Sy Cang 'LDS7' sang t7, cn"

In [87]:
s1

[1] "Pham Sy Cang 'LDS7' sang t7, cn"

In [88]:
a = "one"
b = "two"
c = "three"

In [89]:
paste(a,b,c)

[1] "one two three"

In [90]:
paste(a,b,c, sep="--")

[1] "one--two--three"

In [91]:
paste(a,b,c, sep="")

[1] "onetwothree"

In [92]:
s = "this is a string"
nchar(s)

[1] 16

In [93]:
toupper(s)

[1] "THIS IS A STRING"

In [94]:
tolower(s)

[1] "this is a string"

In [95]:
s_sub = substring(s, 5, 10)

In [96]:
s_sub

[1] " is a "

In [97]:
chartr(" ", "-", s)

[1] "this-is-a-string"

In [98]:
help(chartr)

chartr                  package:base                   R Documentation

_C_h_a_r_a_c_t_e_r _T_r_a_n_s_l_a_t_i_o_n _a_n_d _C_a_s_e_f_o_l_d_i_n_g

_D_e_s_c_r_i_p_t_i_o_n:

     Translate characters in character vectors, in particular from
     upper to lower case or vice versa.

_U_s_a_g_e:

     chartr(old, new, x)
     tolower(x)
     toupper(x)
     casefold(x, upper = FALSE)
     
_A_r_g_u_m_e_n_t_s:

       x: a character vector, or an object that can be coerced to
          character by ‘as.character’.

     old: a character string specifying the characters to be
          translated.  If a character vector of length 2 or more is
          supplied, the first element is used with a warning.

     new: a character string specifying the translations. If a
          character vector of length 2 or more is supplied, the first
          element is used with a warning.

   upper: logical: translate to upper or lower case?.

_D_e_t_a_i_l_s:

     ‘chartr’ translates each character in ‘x’ that is specified in
     ‘old’ to the corresponding character specified in ‘new’.  Ranges
     are supported in the specifications, but character classes and
     repeated characters are not.  If ‘old’ contains more characters
     than new, an error is signaled; if it contains fewer characters,
     the extra characters at the end of ‘new’ are ignored.

     ‘tolower’ and ‘toupper’ convert upper-case characters in a
     character vector to lower-case, or vice versa.  Non-alphabetic
     characters are left unchanged.

     ‘casefold’ is a wrapper for ‘tolower’ and ‘toupper’ provided for
     compatibility with S-PLUS.

_V_a_l_u_e:

     A character vector of the same length and with the same attributes
     as ‘x’ (after possible coercion).

     Elements of the result will be have the encoding declared as that
     of the current locale (see ‘Encoding’) if the corresponding input
     had a declared encoding and the current locale is either Latin-1
     or UTF-8.  The result will be in the current locale's encoding
     unless the corresponding input was in UTF-8, when it will be in
     UTF-8 when the system has Unicode wide characters.

_S_e_e _A_l_s_o:

     ‘sub’ and ‘gsub’ for other substitutions in strings.

_E_x_a_m_p_l_e_s:

     x <- "MiXeD cAsE 123"
     chartr("iXs", "why", x)
     chartr("a-cX", "D-Fw", x)
     tolower(x)
     toupper(x)
     
     ## "Mixed Case" Capitalizing - toupper( every first letter of a word ) :
     
     .simpleCap <- function(x) {
         s <- strsplit(x, " ")[[1]]
         paste(toupper(substring(s, 1, 1)), substring(s, 2),
               sep = "", collapse = " ")
     }
     .simpleCap("the quick red fox jumps over the lazy brown dog")
     ## ->  [1] "The Quick Red Fox Jumps Over The Lazy Brown Dog"
     
     ## and the better, more sophisticated version:
     capwords <- function(s, strict = FALSE) {
         cap <- function(s) paste(toupper(substring(s, 1, 1)),
                       {s <- substring(s, 2); if(strict) tolower(s) else s},
                                  sep = "", collapse = " " )
         sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
     }
     capwords(c("using AIC for model selection"))
     ## ->  [1] "Using AIC For Model Selection"
     capwords(c("using AIC", "for MODEL selection"), strict = TRUE)
     ## ->  [1] "Using Aic"  "For Model Selection"
     ##                ^^^        ^^^^^
     ##               'bad'       'good'
     
     ## -- Very simple insecure crypto --
     rot <- function(ch, k = 13) {
        p0 <- function(...) paste(c(...), collapse = "")
        A <- c(letters, LETTERS, " '")
        I <- seq_len(k); chartr(p0(A), p0(c(A[-I], A[I])), ch)
     }
     
     pw <- "my secret pass phrase"
     (crypw <- rot(pw, 13)) #-> you can send this off
     
     ## now ``decrypt'' :
     rot(crypw, 54 - 13) # -> the original:
     stopifnot(identical(pw

In [101]:
char_list = strsplit(s, " ")

In [102]:
word_list = unlist(char_list)
word_list

[1] "this"   "is"     "a"      "string"

In [103]:
sort(word_list)

[1] "a"      "is"     "string" "this"

In [104]:
sort(word_list, decreasing=TRUE)

[1] "this"   "string" "is"     "a"

### DATE TIME

In [105]:
print(date())

[1] "Sat Jan  9 03:58:09 2021"


In [107]:
print(Sys.Date())

[1] "2021-01-09"


In [108]:
d1 = "20-10-2020"

In [109]:
d1

[1] "20-10-2020"

In [113]:
as.Date(d1, format("%d-%m-%Y"))

[1] "2020-10-20"

In [114]:
format(Sys.Date(), "%d/%m/%Y")

[1] "09/01/2021"

In [115]:
example(difftime)


difftm> ## No test: 
difftm> ##D (z <- Sys.time() - 3600)
difftm> ##D Sys.time() - z                # just over 3600 seconds.
difftm> ##D 
difftm> ##D ## time interval between release days of R 1.2.2 and 1.2.3.
difftm> ##D ISOdate(2001, 4, 26) - ISOdate(2001, 2, 26)
difftm> ##D 
difftm> ##D as.difftime(c("0:3:20", "11:23:15"))
difftm> ##D as.difftime(c("3:20", "23:15", "2:"), format = "%H:%M") # 3rd gives NA
difftm> ##D (z <- as.difftime(c(0,30,60), units = "mins"))
difftm> ##D as.numeric(z, units = "secs")
difftm> ##D as.numeric(z, units = "hours")
difftm> ##D format(z)
difftm> ## End(No test)
difftm> 
difftm> 
