# Review Chapter 6 & 7

In [2]:
## Ex1
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

# Encode survey_vector as a factor: survey_factor
factor_survey = factor(survey_vector)
# Print survey_factor
print(factor_survey)
# Print levels of survey_factor
print(levels(factor_survey))
# Print nlevels of survey_factor
print(nlevels(factor_survey))
# How many elements of each factor?


[1] R R L L R R C C
Levels: C L R
[1] "C" "L" "R"
[1] 3


In [3]:
## Ex2
# Create my_vector: 1 up to 10
my_vector = c(1:10)
# Create my_matrix = (3x3): 1 up to 9
my_matrix = matrix(c(1:9), nrow=3)
# Create my_factor from sizes
sizes <-c("M","S","L","L","M")
my_factor = factor(sizes)
# Construct my_list with the three data structures above
my_list = list(my_vector, my_matrix, my_factor)
# Construct my_super_list with the four data structures above
my_super_list = list(my_vector, my_matrix, my_factor, my_list)
# Display structure of my_super_list (Use str())
str(my_super_list)
# Print my_matrix, sum of my_matrix, sum of even elements in my_matrix
print(my_matrix)
print(sum(my_matrix))
print(sum(my_matrix[my_matrix%%2 ==0]))


List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
  ..$ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] 45
[1] 20


In [20]:
n = 1000
num = sample(1:10000,n,replace=TRUE)

findPrime <- function(x = 0){

  primes <- c()

  # Prime finder
  primes <- sapply(X = x,FUN =  function(x) {
    ifelse(any(x %% (2:(x - 1)) == 0), F, T)}
  )

  # Select primes                 
  primes <- x[primes]

  return(primes)
}

In [21]:
list_prime = findPrime(num)
class(list_prime)

[1] "integer"

In [24]:
print(list_prime[1:16])

 [1] 8087  937  467 7331 6607 3491 9463 6311 2143 2143 4051 9643 1439 2851 2203
[16] 6397


In [25]:
my_matrix = matrix(list_prime[1:16], nrow=4)
print(my_matrix)

     [,1] [,2] [,3] [,4]
[1,] 8087 6607 2143 1439
[2,]  937 3491 2143 2851
[3,]  467 9463 4051 2203
[4,] 7331 6311 9643 6397


In [26]:
print(sum(diag(my_matrix)))

[1] 22026


In [ ]:
## Ex4: 
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Ex3)

# Use apply to calculate the min of the rows across all the matrices.

# Use apply to calculate the max of the columns across all the matrices.

# Use apply to calculate the sum of each matrix in my_array

In [28]:
matrix1 = matrix(list_prime[17:32], nrow=4)

In [31]:
my_array = array(c(my_matrix,matrix1),dim = c(4,4,2))
print(my_array)

, , 1

     [,1] [,2] [,3] [,4]
[1,] 8087 6607 2143 1439
[2,]  937 3491 2143 2851
[3,]  467 9463 4051 2203
[4,] 7331 6311 9643 6397

, , 2

     [,1] [,2] [,3] [,4]
[1,] 1913 4481 4217  877
[2,] 9629 1801 8111 2917
[3,] 6983 7549 6113 6829
[4,] 6833 2333 3929 1039



In [34]:
apply(my_matrix, 1, FUN=min)

[1] 1439  937  467 6311

In [35]:
apply(matrix1, 1, FUN=min)

[1]  877 1801 6113 1039

In [36]:
apply(my_matrix, 1, FUN=max)

[1] 8087 3491 9463 9643

In [37]:
apply(matrix1, 1, FUN=max)

[1] 4481 9629 7549 6833

In [44]:
apply(my_array, 1, FUN=sum)

[1] 29764 31880 43658 43816

In [43]:
example(apply)


apply> ## Compute row and column sums for a matrix:
apply> x <- cbind(x1 = 3, x2 = c(4:1, 2:5))

apply> dimnames(x)[[1]] <- letters[1:8]

apply> apply(x, 2, mean, trim = .2)
x1 x2 
 3  3 

apply> col.sums <- apply(x, 2, sum)

apply> row.sums <- apply(x, 1, sum)

apply> rbind(cbind(x, Rtot = row.sums), Ctot = c(col.sums, sum(col.sums)))
     x1 x2 Rtot
a     3  4    7
b     3  3    6
c     3  2    5
d     3  1    4
e     3  2    5
f     3  3    6
g     3  4    7
h     3  5    8
Ctot 24 24   48

apply> stopifnot( apply(x, 2, is.vector))

apply> ## Sort the columns of a matrix
apply> apply(x, 2, sort)
     x1 x2
[1,]  3  1
[2,]  3  2
[3,]  3  2
[4,]  3  3
[5,]  3  3
[6,]  3  4
[7,]  3  4
[8,]  3  5

apply> ## keeping named dimnames
apply> names(dimnames(x)) <- c("row", "col")

apply> x3 <- array(x, dim = c(dim(x),3),
apply+ 	    dimnames = c(dimnames(x), list(C = paste0("cop.",1:3))))

apply> identical(x,  apply( x,  2,  identity))
[1] TRUE

apply> identical(x3, apply(x3, 2:3, identity))